on: [push]

jobs:
  test_job:
    runs-on: ubuntu-latest
    name: Run tests
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run tests step
        uses: ./testing
        id: test
